"""Golden tests: reference cases 02 to 05 (JuriscalcWeb, generated on 03/07/2026).

Generated by browser automation against the TJDFT's public calculator
(https://juriscalc.tjdft.jus.br/publico/calculos). Parameters and conventions in
docs/REFERENCE_CASES.md.

Guaranteed parity: **to the cent** in monetary amounts. Displayed interest percentages
tolerate ±0.000001 (JuriscalcWeb computes in float64 and the 6th decimal oscillates; this
engine is exact Decimal).
"""

from datetime import date
from decimal import Decimal

import pytest

from debt_engine.interest import fixed_monthly_pct, interest_amount, legal_interest_pct
from tests.helpers import adjust_tjdft, cents, pct6

FINAL = date(2026, 5, 22)


class TestCase02LongFixedInterest:
    """R$ 10,000.00 on 15/03/2020; fixed 1 % per month since 15/03/2020."""

    def test_adjusted_amount(self, repo):
        assert cents(adjust_tjdft(repo, "10000.00", "2020-03")) == Decimal("14253.07")

    def test_exact_75_months(self):
        assert fixed_monthly_pct("1.0", date(2020, 3, 15), FINAL) == Decimal("75.0")

    def test_interest_amount(self, repo):
        adjusted = adjust_tjdft(repo, "10000.00", "2020-03")
        interest = interest_amount(adjusted, Decimal("75.0"))
        assert cents(interest) == Decimal("10689.80")

    def test_total(self, repo):
        adjusted = adjust_tjdft(repo, "10000.00", "2020-03")
        total = adjusted + interest_amount(adjusted, Decimal("75.0"))
        assert cents(total) == Decimal("24942.87")


class TestCase03LegalInterestTimeline:
    """R$ 10,000.00 on 15/03/2020; legal interest since 15/03/2020: crosses 1 % per month
    (until 29/08/2024) and the Legal Rate (since 30/08/2024)."""

    def test_legal_pct(self, repo):
        pct = legal_interest_pct(repo, date(2020, 3, 15), FINAL)
        assert abs(pct6(pct) - Decimal("67.427077")) <= Decimal("0.000001")

    def test_interest_amount(self, repo):
        adjusted = adjust_tjdft(repo, "10000.00", "2020-03")
        interest = interest_amount(adjusted, legal_interest_pct(repo, date(2020, 3, 15), FINAL))
        assert cents(interest) == Decimal("9610.43")

    def test_total(self, repo):
        # line total = displayed components added (as on the statement):
        # 14,253.07 + 9,610.43 = 23,863.50, the same as JuriscalcWeb
        adjusted = adjust_tjdft(repo, "10000.00", "2020-03")
        interest = interest_amount(adjusted, legal_interest_pct(repo, date(2020, 3, 15), FINAL))
        assert cents(adjusted) + cents(interest) == Decimal("23863.50")


class TestCase04MultipleInstallments:
    """Three installments with different due dates; legal interest from the service of process
    (01/06/2023, later than every due date)."""

    INSTALLMENTS = [
        ("1850.00", "2022-03", "2240.58", "647.05", "2887.63"),
        ("1850.00", "2022-04", "2202.91", "636.17", "2839.08"),
        ("1920.00", "2022-11", "2255.88", "651.47", "2907.35"),
    ]

    def test_legal_pct_since_service(self, repo):
        pct = legal_interest_pct(repo, date(2023, 6, 1), FINAL)
        assert abs(pct6(pct) - Decimal("28.878689")) <= Decimal("0.000001")

    @pytest.mark.parametrize("amount,month,adjusted_ref,interest_ref,total_ref", INSTALLMENTS)
    def test_each_installment(self, repo, amount, month, adjusted_ref, interest_ref, total_ref):
        adjusted = adjust_tjdft(repo, amount, month)
        assert cents(adjusted) == Decimal(adjusted_ref)
        pct = legal_interest_pct(repo, date(2023, 6, 1), FINAL)
        interest = interest_amount(adjusted, pct)
        assert cents(interest) == Decimal(interest_ref)
        assert cents(adjusted + interest) == Decimal(total_ref)

    def test_grand_total(self, repo):
        pct = legal_interest_pct(repo, date(2023, 6, 1), FINAL)
        total = Decimal("0")
        for amount, month, *_ in self.INSTALLMENTS:
            adjusted = adjust_tjdft(repo, amount, month)
            total += cents(adjusted + interest_amount(adjusted, pct))
        assert total == Decimal("8634.06")


@pytest.fixture(scope="module")
def total_a_case05(repo):
    adjusted = adjust_tjdft(repo, "134000.00", "2022-03")
    interest = interest_amount(adjusted, legal_interest_pct(repo, date(2026, 5, 15), FINAL))
    return cents(adjusted) + cents(interest)


class TestCase05FineAndFees523:
    """Case 01 + fine and fees of CPC art. 523, §1 (10 % each).

    Mechanics confirmed on the official statement: the base of both is the total (A) =
    adjusted + interest; "creditor's amount" = A + fine; "calculation total" = A + fine + fees
    (the fees do not belong to the creditor).

    Known R$ 0.01 divergence: JuriscalcWeb displays 178,599.64 and 194,835.97, values that do
    NOT add up with its own displayed lines (162,363.32 + 16,236.33 = 178,599.65), an effect
    of its internal float64 aggregation. This engine is internally consistent: every total is
    the exact sum of the displayed components (CPC art. 524, I, itemised statement)."""

    def test_gross_total_a(self, total_a_case05):
        assert total_a_case05 == Decimal("162363.32")

    def test_fine_523(self, total_a_case05):
        assert cents(total_a_case05 * Decimal("0.10")) == Decimal("16236.33")

    def test_fee_523(self, total_a_case05):
        assert cents(total_a_case05 * Decimal("0.10")) == Decimal("16236.33")

    def test_creditor_amount_consistent_sum(self, total_a_case05):
        fine = cents(total_a_case05 * Decimal("0.10"))
        assert total_a_case05 + fine == Decimal("178599.65")  # JuriscalcWeb shows .64

    def test_calculation_total_consistent_sum(self, total_a_case05):
        fine = fees = cents(total_a_case05 * Decimal("0.10"))
        assert total_a_case05 + fine + fees == Decimal("194835.98")  # JuriscalcWeb shows .97
