"""Golden: reference case 11, the São Paulo court's practical table (Dr. Calc, 07/07/2026).

Generated by automation against Dr. Calc (drcalc.net), index "TJSP (INPC/IPCA-15 - Law
14905)", update date June/2026, no interest.

Conventions DECODED empirically (month-by-month factors at the boundary):
* The TJSP table applies INPC up to the month JUL/2024 and IPCA-15 from AUG/2024: one month
  BEFORE the TJDFT switch (full IPCA from SEP/2024): the Sep/2024 table, the first under Law
  14,905, already incorporated August's IPCA-15.
* "Table of month M" = indices up to the month M-1 (the Jun/2026 table applies indices up to
  May/2026): in the engine, adjust_until = M-1.
* Parity to the cent in 8 of 9 values. The 1996 case (30 years of accumulation) diverges
  R$ 0.02: the official table publishes FACTORS rounded to 6 decimals and Dr. Calc uses them;
  this engine does the exact product of the official IBGE indices in Decimal, a defensible
  and documented position.
"""

from decimal import ROUND_HALF_UP, Decimal

import pytest

from debt_engine.calculation import adjustment_factor
from debt_engine.indices import IndexDataError

UNTIL = "2026-05"  # table of June/2026


def adjust(repo, amount: str, month: str) -> Decimal:
    raw = Decimal(amount) * adjustment_factor(repo, "tjsp", month, UNTIL)
    return raw.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


class TestCase11TjspTable:
    def test_installment_crossing_the_switch(self, repo):
        # R$ 1,000.00 on 15/03/2020 -> Dr. Calc: 1,433.87
        assert adjust(repo, "1000.00", "2020-03") == Decimal("1433.87")

    def test_installment_after_the_switch_pure_ipca15(self, repo):
        # R$ 2,500.00 on 10/01/2025 -> Dr. Calc: 2,689.21
        assert adjust(repo, "2500.00", "2025-01") == Decimal("2689.21")

    @pytest.mark.parametrize(
        "month,expected",
        [
            ("2024-07", "1098.24"),  # last INPC month
            ("2024-08", "1095.39"),  # first IPCA-15 month (0.19 % ≠ INPC -0.14 %)
            ("2024-09", "1093.32"),
            ("2024-10", "1091.90"),
            ("2024-11", "1086.03"),
            ("2024-12", "1079.34"),
        ],
    )
    def test_boundary_month_by_month(self, repo, month, expected):
        assert adjust(repo, "1000.00", month) == Decimal(expected)

    def test_30_year_accumulation_with_documented_tolerance(self, repo):
        # R$ 1,000.00 on 15/05/1996 -> Dr. Calc: 6,039.21; exact engine: 6,039.23
        # (the official table's factor is published with 6 decimals; our product is exact)
        ours = adjust(repo, "1000.00", "1996-05")
        assert abs(ours - Decimal("6039.21")) <= Decimal("0.02")
        assert ours == Decimal("6039.23")

    def test_before_1995_explicit_error(self, repo):
        with pytest.raises(IndexDataError, match="1995-08"):
            adjustment_factor(repo, "tjsp", "1994-01", UNTIL)

    def test_new_single_series_work(self, repo):
        # IPCA-15 and IGP-DI as direct series
        assert adjustment_factor(repo, "ipca15", "2025-01", UNTIL) > 1
        assert adjustment_factor(repo, "igpdi", "2025-01", UNTIL) > 1
