"""Golden: reference case 12, dated entries (Dr. Calc, 07/07/2026).

Generated by automation against Dr. Calc ("court debt spreadsheet", TJSP index, update
June/2026, no interest). Mechanics DECODED:

* Dr. Calc's "debt installment" = an installment OF THE DEBT (our normal installments): adds to
  the main table with its own adjustment and interest;
* "court fee" and "procedural expense": adjusted from their own date, ADD after the subtotal,
  NO interest;
* "discount/abatement": adjusted from its own date (NOT nominal), SUBTRACTS, no interest.

Expected values (update Jun/2026 -> adjust_until 2026-05):
  credit  10,000.00 (15/01/2023) -> 11,694.55
  amount   2,000.00 (10/06/2024) ->  2,201.97   | subtotal 13,896.52
  fee        500.00 (20/03/2025) ->    530.72 (+)
  discount   300.00 (10/01/2026) ->    309.07 (-)
  GRAND TOTAL 14,118.17
"""

from datetime import date
from decimal import Decimal

import pytest

from debt_engine.calculation import (
    CalculationInputError,
    CalculationParameters,
    DatedEntry,
    Installment,
    calculate,
)


@pytest.fixture(scope="module")
def result(repo):
    return calculate(
        repo,
        [
            Installment(Decimal("10000.00"), date(2023, 1, 15), "Principal credit"),
            Installment(Decimal("2000.00"), date(2024, 6, 10), "Partial payment"),
        ],
        CalculationParameters(
            final_date=date(2026, 6, 30),
            adjust_until="2026-05",
            index="tjsp",
            interest_regime="none",
            entries=(
                DatedEntry("court_fee", "Court fees", Decimal("500.00"), date(2025, 3, 20)),
                DatedEntry("discount", "Discount", Decimal("300.00"), date(2026, 1, 10)),
            ),
        ),
    )


class TestCase12DatedEntries:
    def test_installments_to_the_cent(self, result):
        assert result.lines[0].adjusted == Decimal("11694.55")
        assert result.lines[1].adjusted == Decimal("2201.97")
        assert result.gross_total == Decimal("13896.52")

    def test_court_fee_adjusted_from_its_own_date(self, result):
        fee = result.entries[0]
        assert fee.entry.kind == "court_fee"
        assert fee.adjusted == Decimal("530.72")

    def test_discount_adjusted_not_nominal(self, result):
        discount = result.entries[1]
        assert discount.entry.kind == "discount"
        assert discount.adjusted == Decimal("309.07")

    def test_dr_calc_grand_total(self, result):
        assert result.total_fees_and_expenses == Decimal("530.72")
        assert result.total_discounts == Decimal("309.07")
        assert result.enforceable_amount == Decimal("14118.17")
        assert result.grand_total == Decimal("14118.17")

    def test_as_dict_carries_the_entries(self, result):
        d = result.as_dict()
        assert d["totals"]["fees_and_expenses"] == "530.72"
        assert d["totals"]["discounts"] == "309.07"
        assert d["entries"][0]["adjusted"] == "530.72"
        assert d["entries"][1]["on"] == "2026-01-10"

    def test_523_accrues_on_the_enforceable_amount_with_entries(self, repo):
        result = calculate(
            repo,
            [Installment(Decimal("10000.00"), date(2023, 1, 15))],
            CalculationParameters(
                final_date=date(2026, 6, 30),
                adjust_until="2026-05",
                index="tjsp",
                interest_regime="none",
                fine_523_pct=Decimal("10"),
                entries=(
                    DatedEntry("court_fee", "Court fees", Decimal("500.00"), date(2025, 3, 20)),
                    DatedEntry("discount", "Payment", Decimal("300.00"), date(2026, 1, 10)),
                ),
            ),
        )
        enforceable = Decimal("11694.55") + Decimal("530.72") - Decimal("309.07")
        assert result.enforceable_amount == enforceable
        assert result.fine_523 == (enforceable * Decimal("0.10")).quantize(Decimal("0.01"))

    def test_invalid_kind_is_an_explicit_error(self, repo):
        with pytest.raises(CalculationInputError, match="entry kind"):
            calculate(
                repo,
                [Installment(Decimal("100.00"), date(2024, 1, 1))],
                CalculationParameters(
                    final_date=date(2026, 6, 30),
                    adjust_until="2026-05",
                    interest_regime="none",
                    entries=(DatedEntry("credit", "x", Decimal("1.00"), date(2024, 1, 1)),),
                ),
            )

    def test_without_entries_nothing_changes(self, repo):
        """Regression: old goldens intact (enforceable == A without deductions)."""
        result = calculate(
            repo,
            [Installment(Decimal("10000.00"), date(2023, 1, 15))],
            CalculationParameters(
                final_date=date(2026, 6, 30),
                adjust_until="2026-05",
                index="tjsp",
                interest_regime="none",
            ),
        )
        assert result.enforceable_amount == result.gross_total
        assert result.total_fees_and_expenses == Decimal("0")
